name: asc
channels:
  - utils
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py37h540881e_1004
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2021.10.8=ha878542_0
  - cffi=1.15.0=py37h036bc23_0
  - cryptography=36.0.0=py37h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - debugpy=1.5.1=py37hcd2ae1e_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - idna=3.3=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.8.0=py37h6531663_0
  - ipython=7.31.1=py37h89c1867_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.1=py37h89c1867_0
  - jpeg=9d=h36c2ea0_0
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py37h89c1867_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libdeflate=1.8=h7f98852_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgomp=11.2.0=h1d223b6_11
  - libiconv=1.16=h516909a_0
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.37=h21135ba_2
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtiff=4.3.0=h6f004c6_2
  - libuv=1.42.0=h7f98852_0
  - libwebp-base=1.2.1=h7f98852_0
  - libzlib=1.2.11=h36c2ea0_1013
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h402132d_0
  - mkl_fft=1.3.1=py37h3e078e5_1
  - mkl_random=1.2.2=py37h219a48f_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - nettle=3.6=he412f7d_0
  - numpy-base=1.21.2=py37h79a1101_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.2=h166bdaf_1
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.4.0=py37h0f21c89_0
  - pip=21.3.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.26=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py37h89c1867_5
  - python=3.7.12=hf930737_100_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - utils=1.11.0=py3.7_cuda11.3_cudnn8.2.0_0
  - utils-mutex=1.0=cuda
  - pyzmq=22.3.0=py37h336d617_1
  - readline=8.1=h46c0cb4_0
  - requests=2.27.1=pyhd8ed1ab_0
  - setuptools=60.5.0=py37h89c1867_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.0=h9cd32fc_0
  - tk=8.6.11=h27826a3_1
  - torchaudio=0.11.0=py37_cu113
  - torchinfo=1.6.5=pyhd8ed1ab_0
  - torchvision=0.12.0=py37_cu113
  - tornado=6.1=py37h5e8e339_2
  - traitlets=5.1.1=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.1=ha95c52a_0
  - pip:
    - absl-py==1.0.0
    - appdirs==1.4.4
    - astunparse==1.6.3
    - attrs==21.4.0
    - audioread==2.1.9
    - cached-property==1.5.2
    - cachetools==5.0.0
    - certifi==2021.10.8
    - charset-normalizer==2.0.10
    - cycler==0.11.0
    - dcase-util==0.2.19
    - flatbuffers==2.0
    - fonttools==4.33.1
    - future==0.18.2
    - gast==0.5.3
    - google-auth==2.6.6
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.44.0
    - h5py==3.6.0
    - importlib-metadata==4.10.0
    - importlib-resources==5.4.0
    - jams==0.3.4
    - joblib==1.1.0
    - jsonschema==4.4.0
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.2
    - libclang==14.0.1
    - librosa==0.8.1
    - llvmlite==0.36.0
    - markdown==3.3.6
    - matplotlib==3.5.1
    - mir-eval==0.6
    - numba==0.53.0
    - numpy==1.20.0
    - oauthlib==3.2.0
    - onnx==1.11.0
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.3.5
    - pathlib==1.0.1
    - pooch==1.5.2
    - prettytable==3.2.0
    - protobuf==3.20.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydot-ng==2.0.0
    - pyparsing==3.0.6
    - pyrsistent==0.18.0
    - python-magic==0.4.25
    - pytz==2021.3
    - pyyaml==6.0
    - requests-oauthlib==1.3.1
    - resampy==0.2.2
    - rsa==4.8
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - sortedcontainers==2.4.0
    - soundata==0.1.1
    - soundfile==0.10.3.post1
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.8.0
    - tensorflow-io-gcs-filesystem==0.25.0
    - termcolor==1.1.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - threadpoolctl==3.0.0
    - torch==1.11.0
    - torchlibrosa==0.0.9
    - torchsort==0.1.9
    - tqdm==4.62.3
    - typing-extensions==4.2.0
    - urllib3==1.26.8
    - validators==0.18.2
    - werkzeug==2.1.1
    - wrapt==1.14.0
    - zipp==3.7.0
    - torch-audiomentations
    - audiomentations